name: Personal Wiki Setup
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

defaults:
  -
    scope:
      path: ""
    values:
      twitter_username: "mitaero"
      ga_id: ""
    scope:
      path: "wiki/" # an empty string here means all files in the project
    values:
      importance: 5
      layout: post
      
